DEVICE := 24FJ128GB202

MCU_SRCS = core_timer.c \
           io.c \
           mcu.c \
           periph/crypto.c \
           periph/gpio.c \
           periph/i2c.c \
           periph/ic.c \
           periph/pwm.c \
           periph/rtc.c \
           periph/spi.c \
           periph/timer.c \
           periph/timer1.c \
           periph/uart.c \
           periph/watchdog.c
