APP=firmware
APP_SRCS = src/block_storage.c \
           src/main.c \
           src/mbr.c \
           src/mpu6050.c \
           src/output.c \
           src/radio.c \
           src/sdcard.c \
           src/status.c

BOARD=boat_controller
FRAMEWORK_ROOT_DIR=$(CURDIR)/../..

include $(FRAMEWORK_ROOT_DIR)/Makefile.include